<?php
/** @var $block \Training\LinkedIn\Block\Customer\Account\AddLinkedinProfile  */

    $isRequired = $block->isLinkedInProfileRequired();
    $isVisible = $block->isLinkedInProfileVisible();
?>

<?php if($isVisible) {?>
<div class="field linkedin_profile">
    <label for="linkedin_profile" class="label"><span><?= $block->escapeHtml(__('LinkedIn Profile')) ?></span></label>
    <div class="control">
        <input type="text" name="linkedin_profile" id="linkedin-profile" title="<?= $block->escapeHtmlAttr(__('LinkedIn Profile')) ?>" class="input-text" <?php if ($isRequired): ?>required="required"<?php endif; ?> data-validate="{'validate-url':true, 'validate-length':true, 'maxTextLength':250}">
    </div>
</div>
<?php } ?>
